language: php

php:
  - 5.6

services:
  - mysql

env:
  - DB=mysql
  
before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - travis_retry composer selfupdate

install:
  # Install Ansible.
  - sudo pip install ansible
  #- wget http://ua2.php.net/get/php-5.6.16.tar.gz/from/this/mirror -O php-5.6.16.tar.gz
  #- tar -xzf php-5.6.16.tar.gz
  #- cd php-5.6.16/ext/pcntl/
  #- phpize && ./configure && make install
  #- ls -la
  - php -i | grep pcntl


before_script:
    #- echo "extension=pcntl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - wget http://files.drush.org/drush.phar
    - chmod +x drush.phar
    - sudo mv drush.phar /usr/local/bin/drush
    #- sudo drush init
    - drush init
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS af_test;create database IF NOT EXISTS af_test;'; fi"

script:
    - drush --version
    - ls -la
    - cd d8 && ansible-playbook reinstall.yml -i 'localhost,' --connection=local --extra-vars="mysql_db=af_test mysql_user=root mysql_pass="
