language: php
sudo: required

php:
  - 5.5
  - 5.6

services:
  - mysql

env:
  - DB=mysql
  
before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

before_script:
    - wget http://files.drush.org/drush.phar
    - chmod +x drush.phar
    - sudo mv drush.phar /usr/local/bin/drush
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS af_test;create database IF NOT EXISTS af_test;'; fi"

script:
    - drush --version
