language: php
sudo: required

php:
  - 5.5
  - 5.6

before_script:
    - wget http://files.drush.org/drush.phar
    - chmod +x drush.phar
    - sudo mv drush.phar /usr/local/bin/drush

script:
    - drush --version
